#!/bin/bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
  *) return;;
esac

# shellcheck source=/dev/null
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# shellcheck source=/dev/null
source ~/.shellrc

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
