#!/bin/bash

export PATH="/usr/local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"

GOPATH="${GOPATH:-"${HOME}/.go"}"
GO_BIN_PATH="${GOPATH}/bin"
if [[ -r "${GO_BIN_PATH}" ]] && [[ -d "${GO_BIN_PATH}" ]]; then
  export PATH="${GO_BIN_PATH}:${PATH}"
fi

CARGO_BIN_PATH="${HOME}/.cargo/bin"
if [[ -r "${CARGO_BIN_PATH}" ]] && [[ -d "${CARGO_BIN_PATH}" ]]; then
  export PATH="${CARGO_BIN_PATH}:${PATH}"
fi

if command -v rustc > /dev/null; then
  RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
  export RUST_SRC_PATH
fi

export DOCKER_BIN_PATH="${HOME}/.docker-bin"
if [[ -r "${DOCKER_BIN_PATH}" ]] && [[ -d "${DOCKER_BIN_PATH}" ]]; then
  export PATH="${DOCKER_BIN_PATH}:${PATH}"
fi

# export NVM_DIR="${HOME}/.nvm"
# if [[ -d "$NVM_DIR" ]] && [[ -r "${NVM_DIR}/nvm.sh" ]]; then
	# # shellcheck source=/dev/null
  # source "${NVM_DIR}/nvm.sh"
# fi

# # shellcheck source=/dev/null
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

