#!/bin/bash

for file in ~/.{aliases,dockerfunc,exports,path}; do
	if [[ -r "${file}" ]] && [[ -f "${file}" ]]; then
		# shellcheck source=/dev/null
		source "${file}"
	fi
done

if [[ -r "/usr/share/autojump/autojump.sh" ]]; then
	# shellcheck source=/dev/null
	source /usr/share/autojump/autojump.sh
fi
