#!/bin/bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
  *) return;;
esac

# shellcheck source=/dev/null
if [[ -f ~/.fzf.bash ]]; then
  source ~/.fzf.bash
else
  if [[ -f /usr/share/doc/fzf/examples/key-bindings.bash ]]; then
    source /usr/share/doc/fzf/examples/key-bindings.bash
  fi

  if [[ -f /usr/share/doc/fzf/examples/completion.bash ]]; then
    source /usr/share/doc/fzf/examples/completion.bash
  fi
fi

if command -v direnv > /dev/null; then
  eval "$(direnv hook bash)"
fi

function main() {
  local cwd
  cwd="$(dirname "${BASH_SOURCE[0]}")"

  # shellcheck source=/dev/null
  source "${cwd}/.dotfiles/shellrc.sh"
}

main
