#!/bin/bash

xrdb -merge ~/.Xresources # theme

# improve mouse/trackpad sensitivity
# there's probably a better place for this...
xinput set-prop 13 298 0.9

xbindkeys # load custom shortcuts
feh --bg-fill ~/.i3/background.png

exec i3 -V >> ~/.i3/logfile 2>&1
