#!/bin/bash

alias ls="ls -H --color=tty"
alias ll="ls -lhH"
alias la="ls -lAhH"

if echo | grep -q --color=tty ""; then
  alias grep="grep --color=tty"
fi

if [[ $(command -v nvim) ]]; then
  alias vim=nvim
fi

if [[ $(command -v xclip) ]]; then
  alias copy="xclip -selection clipboard"
  alias pbcopy="copy"
  alias paste="xclip -selection clipboard -o"
  alias pbpaste="pbpaste"
fi

if [[ $(command -v xdg-open) ]]; then
  alias open="xdg-open"
fi

alias gst="git status"

alias pu="pushd"
alias po="popd"

alias view="vim -R"

# Might be run before autojump.sh is sourced,
# in which case `j` won't be a command yet.
if [[ $(command -v autojump) ]]; then
  alias z="j >/dev/null 2>&1"
fi
